### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Deeroil** [CrackPapaXtreme/ot-harjoitustyo#1]
_Ladattu 13.12. klo 12.40_

Ohjelma piti asentaa uudestaan ensimmäisen asennuksen jälkeen (tehdä uudestaan poetry install) jotta invoke asentui. Omassa projektissani tuli sama ongelma vastaan uudelle laitteelle ladattaessa. En tiedä onko ongelma korjattavissa jotenkin, mutta sen voi huomioida dokumentaatiossa.

Windowsin kanssa ohjelma meni rikki, laitan siitä osion alimmaiseksi. Tein arvostelun käyttäen fuksiläppäriä ja sillä ohjelma toimi ongelmitta.

## Dokumentaatio

Hyvää ja siistiä jälkeä! Dokumentaatio on selkeää  ja docstringit on hyvin tehty, selkeyttää hyvin koodin lukemista.

Pari pientä korjattavaa kohtaa löysin
- Tällä hetkellä ohjelmaan pystyy tekemään käyttäjätunnuksen "admin", vaikka sovelluksen kuvauksessa tämän väitetään olevan estetty. Voisi lisätä pienen maininnan ettei toiminnallisuutta ole vielä toteutettu?
![image](https://user-images.githubusercontent.com/51932469/207375657-8902b926-44de-4f9a-9ac3-d7b417ae7007.png)

  - Toisaalta kyseistä ominaisuutta ei ollut vaatimusmäärittelyssä ollenkaan, ehkä voisi lisätä sinne jos asiaa pidetään tärkeänä
- Asennus ja käyttöönotto-kohdassa on pieni typo "konmentokehote", ei vakavaa tietenkään, ja muita typoja en nopealla vilkaisulla nähnyt.

## Testaus

- Testikattavuus on coveragen mukaan hyvä, mutta testejä on aika vähän, esim yksi testi per luokka.
- Usermgmt testattu useammanlaisessa eri tilanteessa, hyvä! Joka testin alussa toistuu ``` umgr.reset_users_json()```, jonka voisi laittaa setUp-funktion sisään kuten kurssin esimerkeissä on tehty, niin saa toisteisuutta pois koodista.

## Koodi

- Koodi on pääasiassa helppolukuista ja funktiot eivät ole esim. liian pitkiä, mutta json-osiot tuntuvat hieman hankalilta sillä en ole käyttänyt jsonia Pythonilla itse, mutta docstringit auttavat selkolukuisuudessa paljon. On myös mukavaa että pelin generoimat tiedostot luodaan omaan kansioonsa.
- UI on vielä osa index.py -tiedostoa, sen voisi eriyttää omaksi tiedostokseen jotta index.py on yksinkertaisempi.
- Kaikki koodi on src-hakemiston alla ja koodia ei ole juurikansiossa kuten kuuluukin olla. Suurin osa luokista on eritelty omiin tiedostoihinsa, mutta selkeyden vuoksi olisi silti hyvä siirtää osa tiedostoista erillisiin hakemistoihin esim. seuraavalla tavalla:
  - erillinen hakemisto ui, ja sinne käyttöliittymään liittyvät luokat menus.py:stä ja index.py:stä eroteltu tiedosto UI-luokalle
  - toinen hakemisto johon gamemgmt, scoremgmt ja usermgmt, ehkä myös objects.py?

- menus.py on nyt melko pitkä yhdeksi tiedostoksi sillä se on 300 riviä ja sisältää kaksi luokkaa, sen voisi pilkkoa kahdeksi selkeyden takia, toisaalta tiedoston nimi kuvaa ihan selkeästi tiedoston sisältöä.

## Ohjelmasta muita huomioita/parannusehdotuksia

Käyttöliittymää ei tarvinnut arvioida, mutta laitan tähän joitakin huomioita ja parannusehdotuksia myös siitä jos aiot kehittää vielä pidemmälle

- Ohjelma tallentaa aina vain yhden (parhaimman) tuloksen jonka käyttäjä on tehnyt. Hyvä ratkaisu ja antaa muillekin pelaajille mahdollisuuden näkyä listassa, verrattuna tilanteeseen "Tässä on 10 parasta tulosta kaikkein parhaimmalta pelaajalta" :D

- Kellonaika highscorelle voisi olla kiva lisä, esim. jos useampi pelaaja tavoittelee saman päivän aikana highscorea samasta pelistä.

- Peleihin voi nyt lisätä useamman samannimisen pelin. Niissä olevat scoret ovat erillisiä toisistaan (eli ei ole kahtaa kopiota samasta pelistä), niin se on hyvä, mutta nimi-uniikkius peleille olisi yksi parannuskohde.

- Admin password näkyy plaintekstinä sovelluksessa, se olisi visuaalisesti mukava saada vaikka *-merkkien taakse kun kirjoittaa. Salasana on myös plaintextinä tallennettuna tiedostoon, mikä on ok tähän projektiin varmasti, mutta tulevissa projekteissa voisi käyttää salasanan salaamiseen jonkinlaista kryptausta ja salaisuuksia.

- Testasin "Mii" ja "Mii " sekä " Mii" -käyttäjiä, ja nämä kaikki tekivät erillisen käyttäjän. "Mii" ja " Mii" näyttivät highscore-näytöllä samalta käyttäjältä, "Mii " sen sijaan keskittyi eri kohtaan.
![image](https://user-images.githubusercontent.com/51932469/207375522-a12f15eb-24b2-4039-94d7-3c4332a0b29a.png)

  - Tämän ehkäisemiseksi käyttäjän nimeä tallentaessa whitespacet voisi poistaa nimen sivuilta, jolloin ei voitaisi luoda muuten samannimistä käyttäjää, sillä nimen uniikkius tarkistetaan jo koodissa. Toki kaverien kesken sovellusta käyttäessä voi myös olettaa ettei kukaan ala esittämään muiden tilejä. Lisäksi koska vain yksi käyttäjän tulos per peli näkyy, selviää aika pian jos kaksi samaa nimeä näkyy hi-score -listassa.

- Scoresta
  - Score ei ota vastaan float-scoreja, mikä on minusta ihan hyvä valinta. Negatiivinen score sen sijaan käy, joissakin peleissä voi myös käydä niin.
  - Scoren ympärillä olevat whitespacet ei haittaa, vaan esim "   9" on edelleen 9, hyvä ettei hajoa tämmöisissäkään tilanteissa. Score ei myöskään ota vastaan tekstiä joka ei ole numero.
  - Käyttäjän voisi haluta varmisteta (esim salasanalla) kun score annetaan, nyt kuka tahansa voi lisätä scoren

## Windows-ongelma
Ehkä epärelevantti mutta merkitsen ylös silti.

Ohjelma ei toiminut Windowsilla cmd:ssa eikä Powershellillä.

Lisäsin ohjelmaan uuden pelin, ja sen jälkeen pelitulos-näkymästä lisäsin uuden käyttäjän. Tämän jälkeen asetin uuden scoren peliin  tekemälläni käyttäjällä. Ohjelman ruutu meni mustaksi hetkeksi, palasi takaisin aloitusnäyttöön (jossa näkyy pelit) ja ei anna enää avata pelitulosnäkymää kun yrittää painaa auki nappia.
Uusia pelejä voi lisätä ohjelmaan, ja uusia käyttäjiä voi luoda (toiminnallisuus vaikuttaa samalta), mutta ohjelma ei toimi vaan terminaali valittaa että listaindeksi menee rangesta yli.

Tracebackista suurimman osan leikaten pois, ongelma paikantuu scoremgmt.py labmbda-funktioon.
```
"C:\Users\OMISTAJA\Downloads\koodikatselmus-ot-harjoitustyo-master\ot-harjoitustyo-master\src\scoremgmt.py", line 38, in <lambda>
    templist.sort(key=lambda a: int(a[2]), reverse=True)
IndexError: list index out of range
```

Testasin melko samalla tavalla ohjelman suoriutumista fuksiläppärillä, ja en saanut replikoitua ongelmaa, joten kyseessä saattaa olla yhteensopimattomuutta Windowsin kanssa? Silti melko yllättävää.

Kaiken kaikkiaan projekti on hyvällä mallilla!

**Comment by CrackPapaXtreme** [comment]
Kiitos hyvästä palautteesta. :)
